- name: Ensure /var/www/html exists
  file:
    path: /var/www/html
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  become: yes

- name: install nginx
  yum: 
    name:
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes


